name: Cross-platform CI & Release

on:
  push:
    paths: &paths_common
      - '.github/workflows/ci_release.yaml'
      - 'src/*'
      - 'inc/*'
      - 'CMakeLists.txt'
      - '*.cmake'
  pull_request:
    paths: *paths_common
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, windows-2019, windows-2022, macos-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 1
    - name: Build
      id: build
      env:
        archiveName: webhook
      shell: bash
      run: |
        cmake -S . -B build
        cmake --build build --config Release --target ${{env.archiveName}} -j 8
        name="${{env.archiveName}}"
        path="build/bin/${{env.archiveName}}"
        hash=$(git rev-parse --short HEAD)
        echo "package_name=$name" >> $GITHUB_OUTPUT
        echo "package_path=$path" >> $GITHUB_OUTPUT
        echo "commit_hash=$hash" >> $GITHUB_OUTPUT
    - name: Upload Artifacts
      if: github.ref_name == 'master'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.build.outputs.package_name }}
        path: ${{ steps.build.outputs.package_path }}
    - name: Upload Release
      if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ steps.build.outputs.package_path }}
        asset_name: ${{ steps.build.outputs.package_name }}_${{ matrix.os }}_${{ github.ref_name }}
        tag: ${{ github.ref_name }}
        overwrite: true
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ failure() }}
