name: Jenkins Build

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Install Tool
      run: |
        sudo apt install libwww-perl -y
    - name: Post build to jenkins
      env:
        job_name: TestJob
        jenkins_url: https://ohtoai.top/jenkins
        token: ${{secrets.JENKINS_TOKEN}}
      run: |
        GET ${{env.jenkins_url}}/job/${{env.job_name}}/build?token=${{env.token}}
