name: Version Update
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  update-readme-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        git_user_signingkey: true
        git_commit_gpgsign: true
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
    - name: Update README.md
      run: |
        sed -i "s/v[0-9]\+\.[0-9]\+\.[0-9]\+/${{ github.ref_name }}/g" README.md
    - name: Push to GitHub
      if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
      uses: EndBug/add-and-commit@v9.1.1
      with:
        add: README.md
        new_branch: doc_${{ github.ref_name }}
        message: Update Version ${{ github.ref_name }}
        default_author: user_info
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ failure() }}
