name: Version Update
on:
  release:
    types: [published]
jobs:
  update-readme-version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update README.md
      run: |
        sed -i "s/v[0-9]\+\.[0-9]\+\.[0-9]\+/${{ github.ref_name }}/g" README.md
    - name: Push to GitHub
      uses: EndBug/add-and-commit@v9.1.1
      with:
        add: README.md
        new_branch: doc_${{ github.ref_name }}
        message: Update Version
        default_author: user_info
